version: "3.7"
services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "p@ssw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_COLLATION: "Finnish_Swedish_CI_AS"
      TZ: Europe/Stockholm
      MSSQL_DATA_DIR: /input_data/db
    volumes:
      - type: bind
        source: F:\Docker\SQLServer2022\Data
        target: /input_data
      - type: bind
        source: F:\Docker\SQLServer2022\Data\db
        target: /dbdata